import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getAvailableBatches, getSpoilageRecords, recordSpoilage } from "../../services/spoilage.service";
import { getErrorMessage } from "../../utils/getErrorMessage";
import Alert from "../../components/ui/Alert";
import Button from "../../components/ui/Button";
import Input from "../../components/ui/Input";
import Modal from "../../components/ui/Modal";

export default function SpoilagePage() {
 const [open, setOpen] = useState(false); const records = useQuery({ queryKey: ["spoilage-records"], queryFn: getSpoilageRecords });
 return <div className="px-6 py-6 lg:px-8 lg:py-8"><div className="mb-7 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-ink-900">Spoilage</h1><p className="mt-1 text-sm text-ink-500">Keep a permanent history of expired, spoiled, and wasted inventory.</p></div><Button onClick={() => setOpen(true)}>+ Record spoilage</Button></div><Alert type="error" message={records.error ? getErrorMessage(records.error, "Failed to load spoilage history.") : ""}/><div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-stone-50 text-left"><tr><th className="px-5 py-4">Ingredient</th><th className="px-5 py-4">Quantity</th><th className="px-5 py-4">Reason</th><th className="px-5 py-4">Batch expiry</th><th className="px-5 py-4">Recorded</th><th className="px-5 py-4">Notes</th></tr></thead><tbody>{records.data?.map((record) => <tr key={record.id} className="border-t border-stone-100"><td className="px-5 py-4 font-medium">{record.ingredient.name}</td><td className="px-5 py-4">{record.quantity} {record.ingredient.unit?.name}</td><td className="px-5 py-4">{record.reason}</td><td className="px-5 py-4">{record.purchaseItem?.expirationDate ? new Date(record.purchaseItem.expirationDate).toLocaleDateString() : "—"}</td><td className="px-5 py-4">{new Date(record.recordedAt).toLocaleString()}</td><td className="px-5 py-4 text-ink-500">{record.notes ?? "—"}</td></tr>)}{!records.isPending && !records.data?.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-ink-500">No spoilage records yet.</td></tr>}</tbody></table></div></div>{open && <RecordModal close={() => setOpen(false)} />}</div>;
}

function RecordModal({ close }: { close: () => void }) { const qc = useQueryClient(); const [batchId, setBatchId] = useState(""); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState<"SPOILED" | "WASTE">("SPOILED"); const [notes, setNotes] = useState(""); const batches = useQuery({ queryKey: ["available-batches"], queryFn: getAvailableBatches }); const mutation = useMutation({ mutationFn: () => recordSpoilage({ purchaseItemId: Number(batchId), quantity: Number(quantity), reason, notes: notes || undefined }), onSuccess: async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["spoilage-records"] }), qc.invalidateQueries({ queryKey: ["available-batches"] }), qc.invalidateQueries({ queryKey: ["ingredients"] }), qc.invalidateQueries({ queryKey: ["expiration-alerts"] })]); close(); } }); return <Modal title="Record spoilage or waste" onClose={close}><div className="space-y-4"><Alert type="error" message={mutation.error ? getErrorMessage(mutation.error, "Failed to record spoilage.") : ""}/><div><label className="mb-1 block text-sm font-medium">Inventory batch</label><select value={batchId} onChange={(event) => setBatchId(event.target.value)} className="w-full rounded-lg border border-stone-200 p-2 text-sm"><option value="">Select a batch...</option>{batches.data?.map((batch) => <option key={batch.id} value={batch.id}>{batch.ingredient.name} — {batch.remainingQuantity} {batch.ingredient.unit?.name} {batch.expirationDate ? `— expires ${new Date(batch.expirationDate).toLocaleDateString()}` : ""}</option>)}</select></div><Input label="Quantity" type="number" step="0.01" value={quantity} onChange={(event) => setQuantity(event.target.value)} /><div><label className="mb-1 block text-sm font-medium">Reason</label><select value={reason} onChange={(event) => setReason(event.target.value as "SPOILED" | "WASTE")} className="w-full rounded-lg border border-stone-200 p-2 text-sm"><option value="SPOILED">Spoiled</option><option value="WASTE">Waste</option></select></div><Input label="Notes (optional)" value={notes} onChange={(event) => setNotes(event.target.value)} /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={close}>Cancel</Button><Button disabled={!batchId || !Number(quantity)} isLoading={mutation.isPending} onClick={() => mutation.mutate()}>Record</Button></div></div></Modal>; }
